image: node:latest

variables:
    STORYBOOK_DIR: "dist/storybook"

stages:
    - deploy

deploy-library:
    stage: deploy
    tags:
        - docker
    script:
        - npm ci
        - npm run lib:build
        - echo "Содержимое текущей директории"
        - ls
        - echo "Содержимое директории dist:"
        - ls dist
        - echo "CI_SERVER_HOST ${CI_SERVER_HOST}"
        - echo "CI_PROJECT_ID ${CI_PROJECT_ID}"
        - echo "token ${CI_JOB_TOKEN}"
        - echo "@front-components:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
        - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
        - ls -la
        - ls -la dist
        - npm run lib:publish
    artifacts:
        paths:
            - dist/front-components
    only:
        - main

deploy-storybook:
    stage: deploy
    tags:
        - docker
    script:
        - npm ci
        - echo "Билдим storybook"
        - npm run build-storybook
        - mkdir -p public
        - echo "Публикуем storybook"
        - cp -r ${STORYBOOK_DIR}/* public/
    artifacts:
        paths:
            - public
    only:
        - main
