export enum IconType {
  Bell = 'bell',
  ChevronDown = 'chevron-down',
  Column = 'column',
  Drag = 'drag',
  FilterLines = 'filter-lines',
  HamburgerMenu = 'hamburger-menu',
  ImagePlus = 'image-plus',
  KebabMenuDots = 'kebab-menu-dots',
  Minus = 'minus',
  Moon = 'moon',
  Plus = 'plus',
  Settings01 = 'settings-01',
  Settings02 = 'settings-02',
  Sun = 'sun',
  TrendUp01 = 'trend-up-01',
  User01 = 'user-01',
  Users = 'users',
}