import { ReactiveFormsModule } from '@angular/forms';
import { NgFor, NgOptimizedImage } from '@angular/common';
import {
	IconComponent,
	TextComponent,
	ToggleComponent,
	ToggleIconComponent,
	FormFieldComponent,
	InputComponent,
	TextareaComponent,
	DropdownItemComponent,
	DropdownListComponent,
	SelectComponent,
	AvatarComponent,
	NumberPickerComponent,
	DividerComponent,
	ButtonComponent,
	UtilityButtonComponent,
	AvatarButtonComponent,
	CloseButtonComponent,
	BadgeComponent,
	EmptyStateComponent,
	PreviewButtonComponent,
	LinkComponent,
	SkeletonBlockComponent,
	OverlayButtonComponent,
	SpinnerComponent,
	TooltipDirective,
	ImageUploadComponent,
	CalendarComponent,
	DatepickerComponent,
	ProgressCircleComponent,
	ScrollbarComponent,
	TimepickerComponent,
	CheckboxComponent,
	OtpInputComponent,
	TableComponent,
	TabComponent,
	TabsComponent,
	CarouselComponent,
	PaginationDotsComponent,
	ThComponent,
	TableCellDirective,
	TableHeadDirective,
	TableResizedDirective,
	TableThGroupComponent,
	TrComponent,
	DraggableDropdownListComponent,
} from '../../../../front-components/src/lib/components';
import {
	DraggableItemDirective,
	FieldCtrlDirective,
	ItemDirective,
	PopoverTriggerForDirective,
} from '../../../../front-components/src/lib/core/directives';
import { RepeatTimesPipe } from '../../../../front-components/src/lib/core/pipes';
import { ExampleTableTrComponent } from '../example-table-tr/example-table-tr.component';
import { TableDirective } from '../../../../front-components/src/lib/components';
import { LoadPaginationComponent } from '../../../../front-components/src/lib/components/load-pagination/load-pagination.component';

export const standImports = [
	ReactiveFormsModule,
	NgOptimizedImage,
	RepeatTimesPipe,
	FieldCtrlDirective,
	PopoverTriggerForDirective,
	TooltipDirective,
	IconComponent,
	TextComponent,
	ToggleComponent,
	ToggleIconComponent,
	FormFieldComponent,
	InputComponent,
	TextareaComponent,
	DropdownItemComponent,
	DropdownListComponent,
	SelectComponent,
	AvatarComponent,
	NumberPickerComponent,
	DividerComponent,
	ButtonComponent,
	UtilityButtonComponent,
	AvatarButtonComponent,
	CloseButtonComponent,
	BadgeComponent,
	EmptyStateComponent,
	PreviewButtonComponent,
	LinkComponent,
	SkeletonBlockComponent,
	OverlayButtonComponent,
	SpinnerComponent,
	ImageUploadComponent,
	SpinnerComponent,
	CalendarComponent,
	DatepickerComponent,
	ScrollbarComponent,
	TimepickerComponent,
	ProgressCircleComponent,
	CheckboxComponent,
	OtpInputComponent,
	TableComponent,
	ExampleTableTrComponent,
	NgFor,
	CarouselComponent,
	ItemDirective,
	PaginationDotsComponent,
	TabComponent,
	TabsComponent,
	ThComponent,
	TrComponent,
	DraggableItemDirective,
	TableDirective,
	TableCellDirective,
	TableHeadDirective,
	TableResizedDirective,
	TableThGroupComponent,
	LoadPaginationComponent,
	DraggableDropdownListComponent,
];
