import { ReactiveFormsModule } from '@angular/forms';
import { NgFor, NgOptimizedImage } from '@angular/common';
import {
	IconComponent,
	TextComponent,
	ToggleComponent,
	ToggleIconComponent,
	FormFieldComponent,
	InputComponent,
	TextareaComponent,
	DropdownItemComponent,
	DropdownListComponent,
	SelectComponent,
	AvatarComponent,
	NumberPickerComponent,
	DividerComponent,
	ButtonComponent,
	UtilityButtonComponent,
	AvatarButtonComponent,
	CloseButtonComponent,
	BadgeComponent,
	EmptyStateComponent,
	PreviewButtonComponent,
	LinkComponent,
	SkeletonBlockComponent,
	BackdropButtonComponent,
	SpinnerComponent,
	TooltipDirective,
	ImageUploadComponent,
	CalendarComponent,
	DatepickerComponent,
	ProgressCircleComponent,
	ScrollbarComponent,
	TimepickerComponent,
	CheckboxComponent,
	OtpInputComponent,
	TabComponent,
	TabsComponent,
	CarouselComponent,
	PaginationDotsComponent,
	StatusIconComponent,
	DialogHeaderComponent,
	TagComponent,
	ProgressComponent,
	ActionBarComponent,
	ActionBarItemComponent,
} from '../../../../front-components/src/lib/components';
import {
	FieldCtrlDirective,
	ItemDirective,
	PopoverTriggerForDirective,
} from '../../../../front-components/src/lib/core/directives';
import { RepeatTimesPipe } from '../../../../front-components/src/lib/core/pipes';
import { LoadPaginationComponent } from '../../../../front-components/src/lib/components';
import { TableExampleComponent } from '../table-example/table-example.component';

export const standImports = [
	ReactiveFormsModule,
	NgOptimizedImage,
	RepeatTimesPipe,
	FieldCtrlDirective,
	PopoverTriggerForDirective,
	TooltipDirective,
	IconComponent,
	TextComponent,
	ToggleComponent,
	ToggleIconComponent,
	FormFieldComponent,
	InputComponent,
	TextareaComponent,
	DropdownItemComponent,
	DropdownListComponent,
	SelectComponent,
	AvatarComponent,
	NumberPickerComponent,
	DividerComponent,
	ButtonComponent,
	UtilityButtonComponent,
	AvatarButtonComponent,
	CloseButtonComponent,
	BadgeComponent,
	EmptyStateComponent,
	PreviewButtonComponent,
	LinkComponent,
	SkeletonBlockComponent,
	BackdropButtonComponent,
	SpinnerComponent,
	ImageUploadComponent,
	SpinnerComponent,
	CalendarComponent,
	DatepickerComponent,
	ScrollbarComponent,
	TimepickerComponent,
	ProgressCircleComponent,
	CheckboxComponent,
	OtpInputComponent,
	NgFor,
	CarouselComponent,
	ItemDirective,
	PaginationDotsComponent,
	TabComponent,
	TabsComponent,
	LoadPaginationComponent,
	StatusIconComponent,
	TableExampleComponent,
	DialogHeaderComponent,
	TagComponent,
	ProgressComponent,
	ActionBarComponent,
	ActionBarItemComponent,
];
