import { ReactiveFormsModule } from '@angular/forms';
import {
    IconComponent,
    TextComponent,
    ToggleComponent,
    ToggleIconComponent,
    FormFieldComponent,
    InputComponent,
    TextareaComponent,
    DropdownItemComponent,
    DropdownListComponent,
    SelectComponent,
    AvatarComponent,
    NumberPickerComponent,
    DividerComponent,
    ButtonComponent,
    UtilityButtonComponent,
    AvatarButtonComponent,
    CloseButtonComponent,
    BadgeComponent,
    EmptyStateComponent,
    PreviewButtonComponent,
    LinkComponent,
    SkeletonTableComponent,
    SkeletonBlockComponent,
    OverlayButtonComponent,
    CalendarComponent,
    DatepickerComponent,
    SpinnerComponent, TooltipDirective
} from '../../../../front-components/src/lib/components';
import { FieldCtrlDirective, PopoverTriggerForDirective } from '../../../../front-components/src/lib/core/directives';


export const standImports = [
    ReactiveFormsModule,
    FieldCtrlDirective,
    PopoverTriggerForDirective,
    TooltipDirective,
    IconComponent,
    TextComponent,
    ToggleComponent,
    ToggleIconComponent,
    FormFieldComponent,
    InputComponent,
    TextareaComponent,
    DropdownItemComponent,
    DropdownListComponent,
    SelectComponent,
    AvatarComponent,
    NumberPickerComponent,
    DividerComponent,
    ButtonComponent,
    UtilityButtonComponent,
    AvatarButtonComponent,
    CloseButtonComponent,
    BadgeComponent,
    EmptyStateComponent,
    PreviewButtonComponent,
    LinkComponent,
    SkeletonTableComponent,
    SkeletonBlockComponent,
    OverlayButtonComponent,
    SpinnerComponent,
    CalendarComponent,
    DatepickerComponent
]
