import { ExampleDataTable } from '../interface/example-data-table';

export const exampleDataTable: ExampleDataTable[] = [
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: 'https://i.pravatar.cc/300',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
	{
		name: 'Баннер',
		text: 'Баннер и какой то текст',
		imageUrl: '',
		linkUrl: '',
		order: 1,
		user: 'Петров Г.В',
		publicationStartDate: '20 марта 2025 20:02',
		publicationEndDate: '20 марта 2025 20:02',
		isActive: false,
	},
];
